-- 1. Tabel Pesanan (Jobs)
CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_number VARCHAR(20) NOT NULL UNIQUE,
    customer_name VARCHAR(100) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    status VARCHAR(20) DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Rincian Biaya (Job Cost Components)
CREATE TABLE cost_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
    cost_category VARCHAR(20) NOT NULL CHECK (cost_category IN ('RAW_MATERIAL', 'DIRECT_LABOR', 'OVERHEAD')),
    description TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. View untuk Menghitung Total Biaya & HPP per Pesanan
CREATE VIEW job_cost_summary AS
SELECT 
    j.id AS job_id,
    j.job_number,
    j.customer_name,
    j.product_name,
    j.quantity,
    j.status,
    COALESCE(SUM(CASE WHEN c.cost_category = 'RAW_MATERIAL' THEN c.amount ELSE 0 END), 0) AS total_raw_materials,
    COALESCE(SUM(CASE WHEN c.cost_category = 'DIRECT_LABOR' THEN c.amount ELSE 0 END), 0) AS total_direct_labor,
    COALESCE(SUM(CASE WHEN c.cost_category = 'OVERHEAD' THEN c.amount ELSE 0 END), 0) AS total_overhead,
    COALESCE(SUM(c.amount), 0) AS total_job_cost,
    ROUND(COALESCE(SUM(c.amount), 0) / NULLIF(j.quantity, 0), 2) AS unit_cost
FROM jobs j
LEFT JOIN cost_components c ON j.id = c.job_id
GROUP BY j.id;